# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: MobotixIPCamera"
$Body = @'
{
  "Name": "Mobotix IP Camera",
  "ShortName": "MobotixIPCamera",
  "Capability": "MobotixIPCamera",
  "LocalStore": true,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "Enter the username of the configured \"service\" user on the camera",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "Enter the password of the configured \"service\" user on the camera",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "Description": "Select True or False depending on if SSL (HTTPS) should be used to communicate with the camera.",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    },
    {
      "Name": "BypassTlsValidation",
      "DisplayName": "Bypass TLS Validation",
      "Type": "Bool",
      "Description": "If true and 'Use SSL' is enabled, TLS certificate validation is skipped when connecting to the camera. Has no effect when 'Use SSL' is false. Only enable this when the camera's certificate cannot be trusted by the orchestrator server.",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": true
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "Fixed",
  "StorePathValue": "httpd_cert.pem",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

