#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: MobotixIPCamera"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Mobotix IP Camera",
  "ShortName": "MobotixIPCamera",
  "Capability": "MobotixIPCamera",
  "LocalStore": true,
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": true,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "Description": "Enter the username of the configured \"service\" user on the camera",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "Description": "Enter the password of the configured \"service\" user on the camera",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "ServerUseSsl",
      "DisplayName": "Use SSL",
      "Type": "Bool",
      "Description": "Select True or False depending on if SSL (HTTPS) should be used to communicate with the camera. This should always be \"True\"",
      "DependsOn": "",
      "DefaultValue": "true",
      "Required": true
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "StorePathType": "",
  "StorePathValue": "",
  "PrivateKeyAllowed": "Forbidden",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden"
}'

